#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

. $WM_PROJECT_DIR/bin/tools/RunFunctions

createBeamMesh
setInitialPositionBeam -cellZone beam_0 -translate '(0.01 0 0)' -rotateAngle '((0 0 1) 90)'
touch case.foam
