#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

. $WM_PROJECT_DIR/bin/tools/RunFunctions

createCircularBeamMesh -region beamtwo
transformPoints -region beamtwo -rotate-angle  '((0 1 0) 90)'
#setInitialPositionBeam -cellZone beamtwo -region beamtwo -translate '(1.385 -0.423 -0.5)' -rotate "((1 0 0) (-0.90157487255042 0.275354636165218 0.333680346331657))"
setInitialPositionBeam -cellZone beamtwo -region beamtwo -translate '(0 0 0)' -rotate "((1 0 0) (0.90157487255042 -0.275354636165218 -0.333680346331657))"
#setInitialPositionBeam -cellZone beamtwo -region beamtwo -translate '(1.53 0 0)' -rotateAlongVector "(0 1 0) 180"
cp -r constant/beamtwo/polyMesh constant/polyMesh
cp -r 0/beamtwo/* 0/
cp constant/beamtwo/beamProperties constant/
