#!/bin/bash

base_dir="./cables_initialization"
case_dir="mooredFloatingObject"

beams=($(find "$base_dir" -mindepth 1 -maxdepth 1 -type d -exec basename {} \;))

echo "Beams found for cleaning: ${beams[@]}"

# a Function to clean them all
clean_beam()
{    
    local beam="$1"
    local beam_dir="$base_dir/$beam"
    echo "Cleaning $beam"
    (
        cd "$beam_dir" || { echo "Error: Cannot access $beam_dir"; exit 1; }
        ./Allclean
        rm -rf 0/ref* 0/pointW 0/"$beam"
    )
    rm -rf "$case_dir/0.orig/$beam" "$case_dir/constant/$beam"
}


for beam in "${beams[@]}"; do
    clean_beam "$beam"
done

echo "Cleaning completed for all beams."
