#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

canCompile || exit 0    # Dynamic code

runApplication blockMesh


runApplication topoSet
runApplication subsetMesh -overwrite c0 -patch floatingObject
restore0Dir
runApplication setFields

createCircularBeamMesh -region beamone

transformPoints -region beamone -rotate-angle '((0 1 0) 90)' 
setInitialPositionBeam -cellZone beamone -region beamone -translate '(0 0 0)' -rotate "((1 0 0) (0.52849 0.52849 0.66438))"  
#runApplication $(getApplication)

#------------------------------------------------------------------------------
