#!/bin/bash

# Run the beam initialisation case
echo "Running cablesInitialisation/beamone"
(cd cablesInitialisation/beamone && ./Allrun > log.beamMeshing)

# Copy the mesh and fields to the fluid case
cp -r cablesInitialisation/beamone/0 pitzDailyWithBeam/0.orig/beamone
cp -r cablesInitialisation/beamone/constant pitzDailyWithBeam/constant/beamone

# Replace W and theta
\cp pitzDailyWithBeam/0.orig/beamone.org/W pitzDailyWithBeam/0.orig/beamone/
\cp pitzDailyWithBeam/0.orig/beamone.org/theta pitzDailyWithBeam/0.orig/beamone/

# Run the fluid solver
echo "Running pitzDailyWithBeam"
(cd pitzDailyWithBeam && ./Allrun &> log.Allrun)
