#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -f constant/polyMesh/boundary
rm -r constant/beamone/polyMesh
rm -rf 0/beamone
rm -rf 0/ref*
rm -rf 0/pointW
